// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_rating_getFromId from "./routes/api/rating/getFromId.ts";
import * as $api_rating_post from "./routes/api/rating/post.ts";
import * as $api_tosti_getAll from "./routes/api/tosti/getAll.ts";
import * as $api_tosti_getRanked from "./routes/api/tosti/getRanked.ts";
import * as $api_tosti_post from "./routes/api/tosti/post.ts";
import * as $api_tosti_topRankedDaily from "./routes/api/tosti/topRankedDaily.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $leaderboard from "./routes/leaderboard.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LeaderBoard from "./islands/LeaderBoard.tsx";
import * as $QRCode from "./islands/QRCode.tsx";
import * as $TopSpots from "./islands/TopSpots.tsx";
import * as $UploadForm from "./islands/UploadForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/rating/getFromId.ts": $api_rating_getFromId,
    "./routes/api/rating/post.ts": $api_rating_post,
    "./routes/api/tosti/getAll.ts": $api_tosti_getAll,
    "./routes/api/tosti/getRanked.ts": $api_tosti_getRanked,
    "./routes/api/tosti/post.ts": $api_tosti_post,
    "./routes/api/tosti/topRankedDaily.ts": $api_tosti_topRankedDaily,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/leaderboard.tsx": $leaderboard,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LeaderBoard.tsx": $LeaderBoard,
    "./islands/QRCode.tsx": $QRCode,
    "./islands/TopSpots.tsx": $TopSpots,
    "./islands/UploadForm.tsx": $UploadForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
